In [ ]:
!pip install pandas

In [ ]:
import pandas as pd
papers56 = pd.read_csv('data/raw/cogsci_1956-1990.csv')
print(papers56.shape[0])
#notna = papers56["abstract"].dropna()
papers56.info()
papers56.head(20)

In [3]:
from sentence_transformers import SentenceTransformer

# Load model - automatically uses GPU if PyTorch CUDA is available
model = SentenceTransformer("all-mpnet-base-v2")

# Verify GPU is being used
print(model.device)  # Should print: cuda:0

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\Users\werak\projects\masters_thesis\map-of-cognitive-science\.venv\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\werak\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

cuda:0

In [20]:
def encode_paper(paper):
    abstract = paper["abstract"]
    if pd.isna(abstract):
        return None  # Skip papers without abstracts
    embedding = model.encode(abstract)
    return embedding

papers56["embedding"] = papers56.apply(encode_paper, axis=1)

In [21]:
embedded56 = papers56[~papers56["embedding"].isna()]
embedded56

,id,abstract,authorships.author.display_name,authorships.author.id,authorships.author.orcid,authorships.countries,authorships.institutions.display_name,authorships.institutions.id,authorships.is_corresponding,best_oa_location.license,...,open_access.oa_status,primary_location.source.display_name,primary_location.source.id,primary_location.source.issn_l,primary_location.source.type,primary_topic.display_name,publication_date,publication_year,type,embedding
19,https://openalex.org/W2002170215,"Cognitive science is, of course, not really a ...",Herbert A. Simon,https://openalex.org/A5108357701,NaN,US,Carnegie Mellon University,https://openalex.org/I74973139,True,NaN,...,bronze,Cognitive Science,https://openalex.org/S78735424,0364-0213,journal,Cognitive Science and Mapping,1980-01-01,1980,article,"[-0.0034810517, 0.03295612, -0.04766711, -0.06..."
41,https://openalex.org/W1978993273,Research in schizophrenia illustrates that the...,Michael E. Dawson,https://openalex.org/A5110898452,NaN,US,University of Southern California|Southern Cal...,https://openalex.org/I1174212|https://openalex...,True,NaN,...,bronze,Psychophysiology,https://openalex.org/S167723465,0048-5772,journal,Mental Health Research Topics,1990-05-01,1990,review,"[-0.02892376, 0.017825631, 0.004583365, 0.0100..."
53,https://openalex.org/W2130308430,A resource-realistic perspective suggests some...,Christopher Cherniak,https://openalex.org/A5024627342,https://orcid.org/0000-0002-5244-096X,US,"University of Maryland, College Park",https://openalex.org/I66946132,True,NaN,...,bronze,Communications of the ACM,https://openalex.org/S103482838,0001-0782,journal,"Computability, Logic, AI Algorithms",1988-04-01,1988,article,"[0.031051766, 0.07133261, -0.044775818, -0.003..."
77,https://openalex.org/W1979007755,The issues raised by the anti-individualist ar...,Tyler Burge,https://openalex.org/A5080738380,NaN,NaN,NaN,NaN,True,NaN,...,bronze,Notre Dame Journal of Formal Logic,https://openalex.org/S78544662,0029-4527,journal,Space Science and Extraterrestrial Life,1982-07-01,1982,article,"[0.03887882, 0.070493564, -0.03307414, 0.04125..."
82,https://openalex.org/W10672028,"The effects of cholesterol, 7-dehydrocholester...",Bertram C. Bruce,https://openalex.org/A5090063447,https://orcid.org/0000-0001-7392-6945,NaN,NaN,NaN,True,NaN,...,green,European Journal of Biochemistry,https://openalex.org/S4210214924,0014-2956,journal,Advanced Text Analysis Techniques,1978-01-01,1978,article,"[0.033137634, -0.027978117, 0.048303977, 0.005..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,https://openalex.org/W658854855,Issues in Cognitive Psychology and Instruction...,Ronna F. Dillon|Robert J. Sternberg,https://openalex.org/A5020161298|https://opena...,|https://orcid.org/0000-0001-7191-5169,|,NaN,NaN,True|False,cc-by-sa,...,green,NaN,NaN,NaN,NaN,Education and Critical Thinking Development,1986-01-01,1986,book,"[0.00921982, 0.0020467886, -0.030745212, -0.01..."
1101,https://openalex.org/W2271733756,This paper is a review of the state of the art...,Claude M. J. Braun|Marc Andre Ethier|Jacinthe ...,https://openalex.org/A5108528121|https://opena...,||,CA|CA|CA,Université du Québec à Montréal|Concordia Univ...,https://openalex.org/I159129438|https://openal...,True|False|False,NaN,...,bronze,Canadian Journal of Community Mental Health,https://openalex.org/S2764469303,0713-3936,journal,Stroke Rehabilitation and Recovery,1990-09-01,1990,article,"[0.027082216, -0.024101336, -0.029811531, -0.0..."
1103,https://openalex.org/W1992237649,The Yale Al Project is an interdisciplinary re...,Natalie Dehn,https://openalex.org/A5087585549,NaN,US,Yale University,https://openalex.org/I32971472,True,NaN,...,bronze,ACM SIGART Bulletin,https://openalex.org/S4210224649,0163-5719,journal,Natural Language Processing Techniques,1982-01-01,1982,article,"[0.039852366, 0.045867223, -0.045085184, 0.021..."
1115,https://openalex.org/W293393595,This thesis takes as its initial Premise the i...,Ian Cross,https://openalex.org/A5063225709,https://orcid.org/0000-0002-2404-7765,NaN,NaN,NaN,True,NaN,...,green,City Research Online (City University London),https://openalex.org/S4306401940,NaN,repository,Neuroscience and Music Perception,1989-09-01,1989,dissertation,"[-0.025241911, 0.019649312, -0.020392649, 0.00..."
1143,https://openalex.org/W1605012292,Certain techniques are virtually universal in ...,Alexander Sasha Antony Marusich,https://openalex.org/A5010962605,NaN,NaN,NaN,NaN,True,NaN,...,green,Scholars Commons (Wilfrid Laurier University),https://openalex.org/S4306401971,NaN,repository,EEG and Brain-Computer Interfaces,1989-01-01,1989,article,"[0.01049203, -0.007030254, -0.019708639, -0.00..."

In [22]:
embedded56.reset_index(drop=True, inplace=True)
embedded56

,id,abstract,authorships.author.display_name,authorships.author.id,authorships.author.orcid,authorships.countries,authorships.institutions.display_name,authorships.institutions.id,authorships.is_corresponding,best_oa_location.license,...,open_access.oa_status,primary_location.source.display_name,primary_location.source.id,primary_location.source.issn_l,primary_location.source.type,primary_topic.display_name,publication_date,publication_year,type,embedding
0,https://openalex.org/W2002170215,"Cognitive science is, of course, not really a ...",Herbert A. Simon,https://openalex.org/A5108357701,NaN,US,Carnegie Mellon University,https://openalex.org/I74973139,True,NaN,...,bronze,Cognitive Science,https://openalex.org/S78735424,0364-0213,journal,Cognitive Science and Mapping,1980-01-01,1980,article,"[-0.0034810517, 0.03295612, -0.04766711, -0.06..."
1,https://openalex.org/W1978993273,Research in schizophrenia illustrates that the...,Michael E. Dawson,https://openalex.org/A5110898452,NaN,US,University of Southern California|Southern Cal...,https://openalex.org/I1174212|https://openalex...,True,NaN,...,bronze,Psychophysiology,https://openalex.org/S167723465,0048-5772,journal,Mental Health Research Topics,1990-05-01,1990,review,"[-0.02892376, 0.017825631, 0.004583365, 0.0100..."
2,https://openalex.org/W2130308430,A resource-realistic perspective suggests some...,Christopher Cherniak,https://openalex.org/A5024627342,https://orcid.org/0000-0002-5244-096X,US,"University of Maryland, College Park",https://openalex.org/I66946132,True,NaN,...,bronze,Communications of the ACM,https://openalex.org/S103482838,0001-0782,journal,"Computability, Logic, AI Algorithms",1988-04-01,1988,article,"[0.031051766, 0.07133261, -0.044775818, -0.003..."
3,https://openalex.org/W1979007755,The issues raised by the anti-individualist ar...,Tyler Burge,https://openalex.org/A5080738380,NaN,NaN,NaN,NaN,True,NaN,...,bronze,Notre Dame Journal of Formal Logic,https://openalex.org/S78544662,0029-4527,journal,Space Science and Extraterrestrial Life,1982-07-01,1982,article,"[0.03887882, 0.070493564, -0.03307414, 0.04125..."
4,https://openalex.org/W10672028,"The effects of cholesterol, 7-dehydrocholester...",Bertram C. Bruce,https://openalex.org/A5090063447,https://orcid.org/0000-0001-7392-6945,NaN,NaN,NaN,True,NaN,...,green,European Journal of Biochemistry,https://openalex.org/S4210214924,0014-2956,journal,Advanced Text Analysis Techniques,1978-01-01,1978,article,"[0.033137634, -0.027978117, 0.048303977, 0.005..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,https://openalex.org/W658854855,Issues in Cognitive Psychology and Instruction...,Ronna F. Dillon|Robert J. Sternberg,https://openalex.org/A5020161298|https://opena...,|https://orcid.org/0000-0001-7191-5169,|,NaN,NaN,True|False,cc-by-sa,...,green,NaN,NaN,NaN,NaN,Education and Critical Thinking Development,1986-01-01,1986,book,"[0.00921982, 0.0020467886, -0.030745212, -0.01..."
67,https://openalex.org/W2271733756,This paper is a review of the state of the art...,Claude M. J. Braun|Marc Andre Ethier|Jacinthe ...,https://openalex.org/A5108528121|https://opena...,||,CA|CA|CA,Université du Québec à Montréal|Concordia Univ...,https://openalex.org/I159129438|https://openal...,True|False|False,NaN,...,bronze,Canadian Journal of Community Mental Health,https://openalex.org/S2764469303,0713-3936,journal,Stroke Rehabilitation and Recovery,1990-09-01,1990,article,"[0.027082216, -0.024101336, -0.029811531, -0.0..."
68,https://openalex.org/W1992237649,The Yale Al Project is an interdisciplinary re...,Natalie Dehn,https://openalex.org/A5087585549,NaN,US,Yale University,https://openalex.org/I32971472,True,NaN,...,bronze,ACM SIGART Bulletin,https://openalex.org/S4210224649,0163-5719,journal,Natural Language Processing Techniques,1982-01-01,1982,article,"[0.039852366, 0.045867223, -0.045085184, 0.021..."
69,https://openalex.org/W293393595,This thesis takes as its initial Premise the i...,Ian Cross,https://openalex.org/A5063225709,https://orcid.org/0000-0002-2404-7765,NaN,NaN,NaN,True,NaN,...,green,City Research Online (City University London),https://openalex.org/S4306401940,NaN,repository,Neuroscience and Music Perception,1989-09-01,1989,dissertation,"[-0.025241911, 0.019649312, -0.020392649, 0.00..."
70,https://openalex.org/W1605012292,Certain techniques are virtually universal in ...,Alexander Sasha Antony Marusich,https://openalex.org/A5010962605,NaN,NaN,NaN,NaN,True,NaN,...,green,Scholars Commons (Wilfrid Laurier University),https://openalex.org/S4306401971,NaN,repository,EEG and Brain-Computer Interfaces,1989-01-01,1989,article,"[0.01049203, -0.007030254, -0.019708639, -0.00..."